### ISSUE TITLE
Need to document older .mrbak file format

### ISSUE THREAD

**Issue by twindan** [macrium/mrimgx_file_layout#3]
For users who will not upgrade our archives to the latest version, we need to have the older .mrbak file documented so that we can still read the older v8 files.

**Comment by alex-macrium** [comment]
Hi - our aims for this project are to provide Reflect X users with a resource that can be used to guarantee access to backed up Reflect X data independent of any changes in technology or company status might happen - if somehow Macrium as a company no longer exists and older versions of software no longer work on modern operating systems, this project can be used to gain access to data. Hopefully this is an unlikely scenario, but we want to give our customers peace of mind that they are covered no matter what. 

That said, there are some issues that stop us from fully documenting the older formats. One is that they are more complex - as a format that has grown over 10+ years, there are more awkward corners and things that have changed over time and left data layouts that are overly complex. 
Another issue is that there are some third-party components used by the older formats which we have license concerns over - these are things which Macrium have full, perpetual commercial licenses to use, but not redistribute in source code form. 
Likewise, there are a lot of Windows specific conventions, code and data inside the older formats. This is fairly normal for older code built for a Windows-based product, we wanted as much of our open source code as possible to be platform neutral.

We hope to continue to build this offering over time and we are considering what we can do about older formats. We may be able to provide some closed-source binary tools to help the mrimg -> mrimgx conversion (and mrbak -> mrbakx), but this will depend on user demand.
